In [29]:
import numpy as np
import pandas as pd
from scipy.io.arff import loadarff 
import pickle
import ts2vg
import scipy
import sys
from diversity_measure import *

In [30]:
raw_data = loadarff("/home/lfrf/ic/time-series-classification/data/LSST/LSST_TRAIN.arff")
df: pd.DataFrame = pd.DataFrame(raw_data[0])

In [31]:
def save_pickle(data: dict, path: str) -> None:
    # open a file, where you ant to store the data
    with open(path, 'wb') as file:
        pickle.dump(data, file)

In [32]:
# Creating graphs and calculating layer differences (only first 5 rows)
aux_df: pd.DataFrame = df.head(20)
visibility_graphs: np.array = np.zeros((20, 6, 36, 36))
for i in np.arange(len(aux_df["LSST_TRAIN"])):
    for j in np.arange(len(aux_df["LSST_TRAIN"].iloc[i])):
        ts = aux_df["LSST_TRAIN"].iloc[i][j]
        aux_ts = np.array([x for x in ts]).astype(np.float_) # gambiarra
        graph: np.array = ts2vg.NaturalVG().build(aux_ts).adjacency_matrix()
        visibility_graphs[i][j] = graph

In [33]:
ranking: np.array = np.zeros((6, 6))
for i in range(visibility_graphs.shape[0]):
    node_distributions: list = []
    transition_matrices: list = []
    for j in range(visibility_graphs[i].shape[0]):
        graph: np.array = visibility_graphs[i][j]
        node_dist: np.array = node_distribution(graph)
        node_distributions.append(node_dist)
        trans_mat: np.array = transition_matrix(graph)
        transition_matrices.append(trans_mat)
    less_contribute_list: np.array = less_contribute(node_distributions, transition_matrices)
    print(less_contribute_list)
        
        

[4 2 1 5 0 3]
[4 3 5 2 0 1]
[4 2 3 1 0 5]
[4 3 1 2 0 5]
[1 2 5 4 0 3]
[4 3 5 1 0 2]
[5 4 3 1 0 2]
[4 1 2 5 0 3]
[1 2 3 4 0 5]
[3 4 1 2 0 5]
[3 5 4 0 1 2]
[3 1 2 0 4 5]
[1 4 2 3 0 5]
[3 4 2 1 0 5]
[2 1 4 5 0 3]
[2 3 5 4 0 1]
[0 1 5 2 3 4]
[4 3 1 5 0 2]
[3 4 1 2 0 5]
[4 3 1 5 0 2]
