In [12]:
import polars as pl
import pandas as pd
import numpy as np
import scipy
import ts2vg
import matplotlib.pyplot as plt

from diversity_measure import *

In [13]:
data: np.array = scipy.io.arff.loadarff("data/Tiselac/Tiselac_TRAIN.arff")

In [14]:
""" df = pd.DataFrame(columns=["id", "label"])
for i in range(3):
    aux = pd.Series([i, data[0][i][1]])
    df = pd.concat([df, aux])
df.to_csv("teste.csv") """

' df = pd.DataFrame(columns=["id", "label"])\nfor i in range(3):\n    aux = pd.Series([i, data[0][i][1]])\n    df = pd.concat([df, aux])\ndf.to_csv("teste.csv") '

In [15]:
data = data[0][0:20]

In [16]:
visibility_graphs: np.array = np.zeros((10, 10, 23, 23))
for i in range(len(data)):
    node_distributions: list = []
    transition_matrices: list = []
    time_series_set, label = data[i]
    for j in range(len(time_series_set)):
        graph: np.array = ts2vg.NaturalVG().build(time_series_set[j].tolist()).adjacency_matrix()
        node_dist: np.array = node_distribution(graph)
        node_distributions.append(node_dist)
        trans_mat: np.array = transition_matrix(graph)
        transition_matrices.append(trans_mat)
    less_contribute_list: np.array = less_contribute(node_distributions, transition_matrices)
    print(less_contribute_list)


[3 1 6 0 9 2 5 7 4 8]
[2 0 5 1 3 8 4 9 6 7]
[7 9 1 0 3 6 8 4 2 5]
[1 5 6 3 2 0 9 4 7 8]
[0 5 1 4 6 3 2 8 7 9]
[2 1 4 0 6 9 7 5 3 8]
[1 2 3 0 9 6 4 8 5 7]
[0 1 2 4 3 9 6 7 5 8]
[2 6 3 1 5 0 8 7 4 9]
[0 5 2 4 9 3 8 6 1 7]
[0 1 4 6 9 5 2 7 3 8]
[2 4 1 3 9 6 0 5 7 8]
[5 3 9 4 0 1 2 8 6 7]
[1 0 6 2 5 4 9 8 3 7]
[2 6 3 0 8 9 5 7 1 4]
[5 3 1 6 9 2 0 4 7 8]
[2 1 5 0 3 9 8 6 4 7]
[0 3 9 1 2 6 7 8 4 5]
[4 5 6 1 9 0 2 8 3 7]
[5 1 4 9 3 2 6 0 7 8]
